export default class MyAccounts{
get addAccountBtn(){ return $('android=new UiSelector().resourceId("lla-link-account")')};
get pageTitle(){ return $('android=new UiSelector().resourceId("lla-page-name")')}
get accountNumberField(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View/android.view.View[2]/android.view.View[2]/android.widget.EditText')};
get continueBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View/android.view.View[5]/android.view.View/android.view.View/android.widget.Button')};
get ssnField(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View[2]/android.view.View[4]/android.view.View/android.view.View[2]/android.widget.EditText')}
get phoneNumberToggleBtn(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View[2]/android.view.View[3]/android.view.View/android.widget.ToggleButton[2]')};
get ssnNumberToggleBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View[2]/android.view.View[3]/android.view.View/android.widget.ToggleButton[1]')};
get identifyContinueBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View[2]/android.view.View[5]/android.view.View/android.view.View/android.widget.Button')};
get hintBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.view.View/android.view.View[3]/android.view.View/android.view.View')};
get tryAgainBtn() { return $('android=new UiSelector().resourceId("lla-error-button")')};
get linkedAccountNumber(){ return $('//android.view.View[@content-desc="8211990010042372"]/android.widget.TextView')};// adding random number for now.
get hintText(){return $('android=new UiSelector().resourceId("lla-input-hint-text")')};
get errorTitle(){return $('android=new UiSelector().resourceId("lla-error-title")')};
get savedAccountsTab(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[1]/android.view.View[1]/android.view.View/android.widget.TabWidget/android.view.View[2]')};
get linkedAccountsTab(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[1]/android.view.View[1]/android.view.View/android.widget.TabWidget/android.view.View[1]')};
get autoPayAccountLink(){return $('//android.view.View[@content-desc="8211990010024370"]/android.widget.TextView')};
}
