import * as EC from 'wdio-wait-for';
import { StringOrElement } from 'wdio-wait-for/lib/src/utils/element.types';
import { Selector } from 'webdriverio';
export class RegainAccessScreen {
    get rememberEmail() { return $('//android.view.View[@content-desc="Cuenta Residencial" or @content-desc="Residential Account"]/android.view.View')};
    get resetByEmail() { return $('//android.view.View[@content-desc="Email"]/android.view.View')};
    get emailIdField() { return $('android=new UiSelector().resourceId("lla-enter-email")')};
    get sendEmailBtn() { return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[1]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[3]/android.view.View[2]')};
    get doneBtn() { return $('//android.widget.Button[@text="Done" or @text="Terminar"]')}
    get resendLink(){ return $('//android.view.View[@content-desc="Volver a enviar" or @content-desc="Send again"]/android.widget.TextView')};
    get dialogCloseBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[1]/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[1]/android.view.View')};
    get tryAgainBtn(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[1]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View/android.view.View[4]/android.view.View/android.widget.Button')};
    get residentialAccount(){return $('//android.view.View[@content-desc="Recordar email" or @content-desc="Remember Email"]/android.view.View')};
    get accountNumberField(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.widget.EditText')};
    get ssnField(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[5]/android.view.View/android.view.View[2]/android.widget.EditText')};
    get ssnValidateBtn() { return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[6]/android.view.View/android.view.View/android.widget.Button')};
    get validateBtn(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[3]/android.view.View/android.view.View/android.widget.Button')};
    get rememberEmailPopup(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[1]')}; 
    get goToLoginBtn(){ return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.app.Dialog/android.view.View[2]/android.view.View[3]/android.widget.Button')};
   get errorTitle(){return $('android=new UiSelector().resourceId("lla-error-title")')};
   get tryAgainEmailBtn(){return $('android=new UiSelector().resourceId("lla-error-button")')};
   get emailDoneBtn(){return $('/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.view.View[5]/android.widget.Button')} ;
   async waitForButtonEnabled(element: StringOrElement){
        await browser.waitUntil(EC.elementToBeEnabled(element), { timeout: 10000 });
    }
}